apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: test-status-cr
  namespace: default
spec:
  mode: Recommend
  selector:
    namespaces:
      allow:
        - default
  metricsConfig:
    provider: prometheus
  resourceBounds:
    cpu:
      min: 10m
      max: 1000m
    memory:
      min: 64Mi
      max: 1Gi
  updateStrategy: {}
