apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: system
  labels:
    control-plane: webhook-server
    app.kubernetes.io/name: optipod-webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: webhook-server
    app.kubernetes.io/name: optipod-webhook
  ports:
  - name: webhook
    port: 443
    targetPort: 9443
    protocol: TCP
  type: ClusterIP
