apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: selector-debug-policy
  namespace: optipod-system
spec:
  mode: Recommend  # Use Recommend mode to avoid actual changes during debugging
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        test-type: "selector-debug"
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.0
  resourceBounds:
    cpu:
      min: "50m"
      max: "1000m"
    memory:
      min: "32Mi"
      max: "1Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: true
    useServerSideApply: true
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.1
  reconciliationInterval: 30s  # Faster for debugging