apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: update-strategy-ssa-test
  namespace: optipod-system
spec:
  mode: Auto
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        update-strategy-test: "ssa"
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.0
  resourceBounds:
    cpu:
      min: "50m"
      max: "2000m"
    memory:
      min: "32Mi"
      max: "4Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: false
    useServerSideApply: true  # Test Server-Side Apply
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.0
  reconciliationInterval: 1m
