apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: boundary-limits-test
  namespace: optipod-system
spec:
  mode: Recommend  # Use Recommend mode to avoid actual modifications
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        bounds-test: "boundary"
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.0
  resourceBounds:
    cpu:
      min: "100m"    # 0.1 CPU cores
      max: "1500m"   # 1.5 CPU cores
    memory:
      min: "128Mi"   # 128 Mebibytes
      max: "3Gi"     # 3 Gibibytes
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: false
    useServerSideApply: true
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.0
  reconciliationInterval: 1m
