apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-mode-auto-test
  namespace: default
  labels:
    optimize: "true"
    policy-mode-test: "auto"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-mode-auto-test
  template:
    metadata:
      labels:
        app: policy-mode-auto-test
        optimize: "true"
        policy-mode-test: "auto"
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 80
