apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: memory-safety-test
  namespace: optipod-system
spec:
  mode: Recommend
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        error-test: "memory-safety"
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.2  # Higher safety factor for memory safety
  resourceBounds:
    cpu:
      min: "100m"
      max: "2000m"
    memory:
      min: "512Mi"  # Minimum to prevent unsafe decreases
      max: "4Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: false
    useServerSideApply: true
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.0
  reconciliationInterval: 1m