apiVersion: apps/v1
kind: Deployment
metadata:
  name: safety-factor-test
  namespace: default
  labels:
    optimize: "true"
    error-test: "safety-factor"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: safety-factor-test
  template:
    metadata:
      labels:
        app: safety-factor-test
        optimize: "true"
        error-test: "safety-factor"
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "600m"
            memory: "1Gi"
        ports:
        - containerPort: 80
