apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: bounds-above-max-test
  namespace: optipod-system
spec:
  mode: Recommend  # Use Recommend mode to avoid actual modifications
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        bounds-test: "above-max"
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.0
  resourceBounds:
    cpu:
      min: "100m"
      max: "800m"
    memory:
      min: "128Mi"
      max: "1Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: false
    useServerSideApply: true
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.0
  reconciliationInterval: 1m
