apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: dev-policy-single-workload
  namespace: optipod-system
spec:
  mode: Auto
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        app: nginx-web  # Target only nginx-web
  metricsConfig:
    provider: metrics-server
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.2
  resourceBounds:
    cpu:
      min: "50m"
      max: "2000m"
    memory:
      min: "64Mi"
      max: "2Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: true
    updateRequestsOnly: true  # Start simple
    useServerSideApply: true
  reconciliationInterval: 1m