apiVersion: optipod.optipod.io/v1alpha1
kind: OptimizationPolicy
metadata:
  name: missing-metrics-test
  namespace: optipod-system
spec:
  mode: Auto
  selector:
    namespaceSelector:
      matchLabels:
        environment: development
    workloadSelector:
      matchLabels:
        optimize: "true"
        error-test: "missing-metrics"
  metricsConfig:
    provider: nonexistent-provider  # Provider that doesn't exist
    rollingWindow: 5m
    percentile: P90
    safetyFactor: 1.0
  resourceBounds:
    cpu:
      min: "50m"
      max: "2000m"
    memory:
      min: "32Mi"
      max: "4Gi"
  updateStrategy:
    allowInPlaceResize: true
    allowRecreate: false
    updateRequestsOnly: false
    useServerSideApply: true
    limitConfig:
      cpuLimitMultiplier: 1.0
      memoryLimitMultiplier: 1.1
  reconciliationInterval: 1m
